name: Run tests & deploy

on: push

env:
  secrets_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
  secrets_host: ${{ secrets.SSH_HOST }}
  secrets_user: ${{ secrets.SSH_USER }}
  secrets_port: 22
  secrets_digital_ocean: ${{ secrets.DIGITALOCEAN_ACCES_TOKEN }}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.6'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest

  build:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
    # - name: Install SSH Key
    #   uses: shimataro/ssh-key-action@v2
    #   with:
    #     known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    #     key: secrets_private_key
    # - name: Adding Know Host
    #   run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: Deploy with digitalocean
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: $secrets_host
        key: $secrets_private_key
        username: $secrets_user
        port: 22
#        passphrase: "secret_passphrase"
#    - name: Install doctl
#      uses: digitalocean/action-doctl@v2
#      with:
#        token: secrets_digital_ocean

        script: |
          mkdir test
          cd test
          git clone git@github.com:famkepj/flask_joke.git
       
