name: Run tests & deploy

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.6'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest

  build:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
    - name: Deploy with digitalocean
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        username: ${{ secrets.SSH_USER }}
        port: 22


        script: |
# verwijder oude versie
          rm -r /home/flask_joke
# copy nieuwe versie
          git clone https://${{secrets.GITHUB_TOKEN}}@github.com/famkepj/flask_joke.git /home/flask_joke
          echo 'deployment succesful to digital ocean'
